# Generated by Django 4.1.7 on 2023-06-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_doctor_kabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отечество'),
        ),
    ]
