# Generated by Django 4.1.7 on 2023-06-07 08:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_doctor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='kabinet',
            field=models.IntegerField(blank=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+996', max_length=128, region=None, verbose_name='Телефон номер'),
        ),
    ]
