# Generated by Django 4.1.7 on 2023-06-07 08:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_doctor_kabinet_alter_doctor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(null=True, verbose_name='Стаж: '),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='kabinet',
            field=models.IntegerField(null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Отечество'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+996', max_length=128, null=True, region=None, verbose_name='Телефон номер'),
        ),
    ]
